<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-24T07:26:41Z" name="Suite" finished-at="2022-05-24T07:27:01Z" duration-ms="19990">
    <groups>
    </groups>
    <test started-at="2022-05-24T07:26:41Z" name="Test" finished-at="2022-05-24T07:27:01Z" duration-ms="19990">
      <class name="com.corePyramin.LoginPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.corePyramin.LoginPageTest@673bb956]" started-at="2022-05-24T07:26:41Z" name="setup" finished-at="2022-05-24T07:26:49Z" duration-ms="8206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ValidateLoginSucessfull()[pri:0, instance:com.corePyramin.LoginPageTest@673bb956]" started-at="2022-05-24T07:26:49Z" name="ValidateLoginSucessfull" finished-at="2022-05-24T07:26:52Z" duration-ms="2281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateLoginSucessfull -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.corePyramin.LoginPageTest@673bb956]" started-at="2022-05-24T07:26:52Z" name="teardown" finished-at="2022-05-24T07:26:52Z" duration-ms="908" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.corePyramin.LoginPageTest@673bb956]" started-at="2022-05-24T07:26:52Z" name="setup" finished-at="2022-05-24T07:27:00Z" duration-ms="7050" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginPageTitleTest()[pri:0, instance:com.corePyramin.LoginPageTest@673bb956]" started-at="2022-05-24T07:27:00Z" name="loginPageTitleTest" finished-at="2022-05-24T07:27:00Z" duration-ms="11" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PyramidCore---Login] but found [PyramidCore-Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PyramidCore---Login] but found [PyramidCore-Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.corePyramin.LoginPageTest.loginPageTitleTest(LoginPageTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.corePyramin.LoginPageTest@673bb956]" started-at="2022-05-24T07:27:00Z" name="teardown" finished-at="2022-05-24T07:27:01Z" duration-ms="933" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.corePyramin.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
